---
name: Github CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: crystallang/crystal:0.36.0
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make spec
