---
name: CI

permissions: {}

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - "**.md"
  schedule:
    - cron: '0 4 1 * *'
  # Run workflow manually
  workflow_dispatch:

jobs:
  ameba:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: mise dev:deps

      - name: Run static code analysis
        run: mise dev:ameba

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: mise dev:deps

      - name: Run tests
        run: mise dev:spec

  test_macos_arm64:
    runs-on: macos-26
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v3

      # TODO: remove me when https://github.com/crystal-lang/crystal/issues/16746 is fixed
      - name: Fix Crystal shards
        run: mise dev:fix-shards-command

      - name: Install dependencies
        run: mise dev:deps

      - name: Run tests
        run: mise dev:spec

  test_macos_amd64:
    runs-on: macos-26-intel
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v3

      # TODO: remove me when https://github.com/crystal-lang/crystal/issues/16746 is fixed
      - name: Fix Crystal shards
        run: mise dev:fix-shards-command

      - name: Install dependencies
        run: mise dev:deps

      - name: Run tests
        run: mise dev:spec
