---
name: CI

on:
  - push
  - pull_request


jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.8.0

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make spec




  test_macos:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.8.0

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make spec
