---
name: Dockerhub Nightly

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: crystallang/crystal:1.2.0
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make spec

  publish:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nicoladmin/stacker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: nightly
