---
name: Github Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: mise dev:deps

      - name: Run tests
        run: mise dev:spec

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: mise dev:deps

      - name: Generate documentation
        run: mise dev:doc

      - name: Publish to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
