---
name: Release Binaries

on:
  push:
    tags:
      - '*'

jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Build static binaries
        run: mise release:static

      - name: Create release and publish assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

  release_macos_arm64:
    runs-on: macos-26
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install bdw-gc
        run: brew install bdw-gc

      - name: Setup mise
        uses: jdx/mise-action@v3

      # TODO: remove me when https://github.com/crystal-lang/crystal/issues/16746 is fixed
      - name: Fix Crystal shards
        run: mise dev:fix-shards-command

      - name: Install dependencies
        run: mise release:deps

      - name: Build binary
        run: mise release:build
        env:
          OUTPUT_FILE: bin/stacker-darwin-arm64

      - name: Create release and publish assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

  release_macos_amd64:
    runs-on: macos-26-intel
    steps:
      - name: Git checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install bdw-gc
        run: brew install bdw-gc

      - name: Setup mise
        uses: jdx/mise-action@v3

      # TODO: remove me when https://github.com/crystal-lang/crystal/issues/16746 is fixed
      - name: Fix Crystal shards
        run: mise dev:fix-shards-command

      - name: Install dependencies
        run: mise release:deps

      - name: Build binary
        run: mise release:build
        env:
          OUTPUT_FILE: bin/stacker-darwin-amd64

      - name: Create release and publish assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
